"""
Visualization-only script: Normalized Macro F1 (Selectivity over Memorization).

Produces two paper-ready figures from the metrics generated by
`train_linear_probes_on_annotations.py`:

  (A) Point-estimate curve  -> `02_comparison_normalized_f1_scaled.png`
  (B) One curve+band per dispersion metric, configured in DISPERSION_METRICS,
      e.g. `02_comparison_normalized_f1_ci95.png`,
           `02_comparison_normalized_f1_sd196.png`, ...

The dispersion bands use Option 1 (test-set bootstrap): we DO NOT retrain. We
reload the saved probe (`.joblib`) and the activations (`.pkl`), reconstruct the
exact same train/test split as training (same `random_state`, `stratify`,
rare-class filtering), and resample the test-set predictions with replacement.
From the bootstrap replicates we store mean, std (the bootstrap SE) and a set of
percentiles, so any band (percentile CI, mean +- k*SD, ...) can be drawn at plot
time WITHOUT re-bootstrapping. Control (random-permutation) baseline is taken
from the metrics CSV. Results are cached to CSV.

Y-axis shows 0 (the floor); it only dips below 0 if a symmetric SD band does.
"""

import os
from collections import Counter

import numpy as np
import pandas as pd
import joblib
import matplotlib.pyplot as plt
import seaborn as sns
from tqdm import tqdm
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score

# --- CONFIG ---
LLM_USED = "Llama-2-7b-chat-hf"   # "Qwen2.5-14B-Instruct"
DATASET = "generated_prompts"     # "human_centric"
MODEL_DIM = 4096                  # 5120 for Qwen2.5-14B
BASE_DIR = "/home/jcuello/emotion_drift"

# Must match the training run that produced the CSV / models.
DATA_PATH = "/home/jcuello/emotion_drift/data/03_activations/generated_prompts_Llama-2-7b-chat-hf_20251014_203636_FINAL_WITH_RATINGS_AND_CATS.pkl"
SENTIMENT_TARGETS = ['ekman_basic_emotions', 'go_emotions', 'plutchik_wheel']
MIN_SAMPLES_REQUIRED = 5
SPLIT_RANDOM_STATE = 42

# Bootstrap settings
N_BOOTSTRAP = 10000
BOOTSTRAP_SEED = 0
USE_CACHED_BOOTSTRAP = True       # reuse the cached CI CSV if it exists

# Percentiles stored from the bootstrap distribution (lets us redraw any
# percentile band later without re-bootstrapping).
PERCENTILES = [2.5, 5, 16, 25, 75, 84, 95, 97.5]


def _pct_col(p):
    """Column name for a stored percentile, e.g. 2.5 -> 'norm_f1_p2_5'."""
    return f"norm_f1_p{str(p).replace('.', '_')}"


# Dispersion bands to draw around the bootstrap mean. ONE figure per entry.
# `band(d)` takes the per-taxonomy bootstrap DataFrame and returns (lower, upper).
DISPERSION_METRICS = [
    {"key": "ci95", "label": "95% percentile CI [2.5, 97.5]",
     "band": lambda d: (d[_pct_col(2.5)], d[_pct_col(97.5)])},
    {"key": "sd196", "label": r"Mean $\pm$ 1.96$\cdot$SD (normal approx.)",
     "band": lambda d: (d["norm_f1_mean"] - 1.96 * d["norm_f1_std"],
                        d["norm_f1_mean"] + 1.96 * d["norm_f1_std"])},
    {"key": "sd1", "label": r"Mean $\pm$ 1 SD",
     "band": lambda d: (d["norm_f1_mean"] - d["norm_f1_std"],
                        d["norm_f1_mean"] + d["norm_f1_std"])},
    {"key": "sd2", "label": r"Mean $\pm$ 2 SD",
     "band": lambda d: (d["norm_f1_mean"] - 2.0 * d["norm_f1_std"],
                        d["norm_f1_mean"] + 2.0 * d["norm_f1_std"])},
]

# Derived paths
RESULTS_DIR = os.path.join(BASE_DIR, "results", f"probes_{DATASET}_{LLM_USED}")
INPUT_CSV = os.path.join(RESULTS_DIR, f"full_probing_metrics_{LLM_USED}_final_F1.csv")
BOOTSTRAP_CSV = os.path.join(RESULTS_DIR, f"normalized_f1_bootstrap_ci_{LLM_USED}.csv")
FIGURES_DIR = os.path.join(BASE_DIR, "figures", f"probes_{DATASET}_{LLM_USED}")
MODELS_DIR = os.path.join(BASE_DIR, "models")

# Pretty labels for the legend
PRETTY = {
    'ekman_basic_emotions': 'Ekman',
    'go_emotions': 'GoEmotions',
    'plutchik_wheel': 'Plutchik',
}

# Show the normalization formula in a corner box (set False for a cleaner figure)
SHOW_FORMULA = False


def _normalize_f1(f1, control_f1):
    """Selectivity-over-memorization normalization used in training."""
    if control_f1 < 0.99:
        return (f1 - control_f1) / (1.0 - control_f1)
    return 0.0


def _build_test_split(sub, target, layer):
    """Reconstruct the exact (X_test, y_test) used in training for one layer."""
    X_list, y_list = [], []
    for act_row, label in zip(sub['activations'], sub[target]):
        try:
            act = act_row.iloc[layer]['last_token_activation']
        except Exception:
            continue
        if not isinstance(act, np.ndarray):
            continue
        if act.ndim > 1:
            act = act.squeeze()
        if act.shape == (MODEL_DIM,):
            X_list.append(act)
            y_list.append(label)

    if not X_list:
        return None, None
    X = np.stack(X_list)
    y_real = np.array(y_list)

    # Drop rare classes (identical to training).
    counts = Counter(y_real)
    drop = [c for c, n in counts.items() if n < MIN_SAMPLES_REQUIRED]
    if drop:
        keep = ~np.isin(y_real, drop)
        X, y_real = X[keep], y_real[keep]

    if len(X) == 0 or len(np.unique(y_real)) < 2:
        return None, None

    try:
        _, X_test, _, y_test = train_test_split(
            X, y_real, test_size=0.2,
            random_state=SPLIT_RANDOM_STATE, stratify=y_real,
        )
    except ValueError:
        return None, None
    return X_test, y_test


def compute_bootstrap_ci(df):
    """Test-set bootstrap CI for normalized macro F1 (no retraining)."""
    if not os.path.exists(DATA_PATH):
        raise FileNotFoundError(f"Activations not found: {DATA_PATH}")
    nested = pd.read_pickle(DATA_PATH)

    rng = np.random.default_rng(BOOTSTRAP_SEED)
    rows = []

    for target in SENTIMENT_TARGETS:
        df_t = df[df['taxonomy'] == target]
        if df_t.empty or target not in nested.columns:
            continue

        mask = nested[target].apply(lambda x: isinstance(x, list) and len(x) > 0)
        sub = nested[mask].copy()
        sub[target] = sub[target].str[0]

        control_lookup = dict(zip(df_t['layer'], df_t['control_macro_f1']))

        for layer in tqdm(sorted(df_t['layer']), desc=f"Bootstrap {PRETTY.get(target, target)}"):
            model_path = os.path.join(
                MODELS_DIR, f"{DATASET}_{LLM_USED}_{target}_layer_{layer}.joblib"
            )
            if not os.path.exists(model_path):
                continue

            X_test, y_test = _build_test_split(sub, target, layer)
            if X_test is None:
                continue

            clf = joblib.load(model_path)
            y_pred = clf.predict(X_test)
            control_f1 = control_lookup.get(layer, 0.0)

            n = len(y_test)
            boot = np.empty(N_BOOTSTRAP)
            for b in range(N_BOOTSTRAP):
                idx = rng.integers(0, n, n)
                f1b = f1_score(y_test[idx], y_pred[idx], average='macro', zero_division=0)
                boot[b] = _normalize_f1(f1b, control_f1)

            row = {
                'taxonomy': target,
                'layer': layer,
                'norm_f1_mean': float(np.mean(boot)),
                'norm_f1_std': float(np.std(boot, ddof=1)),  # bootstrap SE
            }
            for p in PERCENTILES:
                row[_pct_col(p)] = float(np.percentile(boot, p))
            rows.append(row)

    boot_df = pd.DataFrame(rows)
    boot_df.to_csv(BOOTSTRAP_CSV, index=False)
    print(f"Saved bootstrap CIs: {BOOTSTRAP_CSV}")
    return boot_df


def _style():
    sns.set_theme(style="whitegrid")
    plt.rcParams.update({'font.size': 12})


def _color_map():
    palette = sns.color_palette("tab10", n_colors=len(SENTIMENT_TARGETS))
    return dict(zip(SENTIMENT_TARGETS, palette))


def _finalize(y_max, y_min=0.0, title=None, with_formula=SHOW_FORMULA):
    """Common axis/legend styling.

    0 is always shown as the floor; the axis only extends below 0 if a
    (symmetric) band actually dips negative, so SD bands are never clipped.
    """
    plt.title(title or 'Normalized Macro F1 (Selectivity over Memorization)', fontsize=14)
    plt.xlabel('Layer', fontsize=12)
    plt.ylabel('Normalized Macro F1', fontsize=12)
    pad = max(y_max * 0.08, 0.01)
    bottom = min(0.0, y_min)
    if bottom < 0:
        bottom -= pad  # small margin so a negative band isn't flush to the edge
    plt.ylim(bottom, y_max + pad)
    plt.legend(fontsize=11, title="Taxonomy (H: normalized entropy)", title_fontsize=11)
    plt.grid(True, linestyle='--', alpha=0.5)
    if with_formula:
        plt.text(0.02, 0.02,
                 r"$\mathrm{score} = (F1_{real} - F1_{control}) / (1 - F1_{control})$",
                 transform=plt.gca().transAxes, fontsize=9,
                 verticalalignment='bottom',
                 bbox=dict(boxstyle='round', facecolor='white', alpha=0.8))
    plt.tight_layout()


def plot_point(df, color_map):
    """Figure A: point-estimate curve, no CI."""
    _style()
    plt.figure(figsize=(8, 5))
    y_max = 0.0
    for target in SENTIMENT_TARGETS:
        subset = df[df['taxonomy'] == target].sort_values('layer')
        if subset.empty:
            continue
        ent = subset['imbalance_entropy'].iloc[0]
        plt.plot(subset['layer'], subset['normalized_macro_f1'],
                 marker='o', markersize=4, linewidth=2, color=color_map[target],
                 label=f"{PRETTY.get(target, target)} (H={ent:.2f})")
        y_max = max(y_max, subset['normalized_macro_f1'].max())

    _finalize(y_max)
    path = os.path.join(FIGURES_DIR, "02_comparison_normalized_f1_scaled.png")
    plt.savefig(path, dpi=300)
    plt.close()
    print(f"Saved: {path}")


def plot_dispersion(df, boot_df, color_map, metric):
    """Figure B variant: point-estimate curve + one dispersion band.

    `metric` is an entry of DISPERSION_METRICS; one figure is produced per call.
    """
    _style()
    plt.figure(figsize=(8, 5))
    y_max, y_min = 0.0, 0.0
    for target in SENTIMENT_TARGETS:
        subset = df[df['taxonomy'] == target].sort_values('layer')
        b = boot_df[boot_df['taxonomy'] == target].sort_values('layer')
        if subset.empty or b.empty:
            continue
        ent = subset['imbalance_entropy'].iloc[0]
        c = color_map[target]
        plt.plot(subset['layer'], subset['normalized_macro_f1'],
                 marker='o', markersize=4, linewidth=2, color=c,
                 label=f"{PRETTY.get(target, target)} (H={ent:.2f})")
        lower, upper = metric['band'](b)
        plt.fill_between(b['layer'], lower, upper, color=c, alpha=0.22)
        y_max = max(y_max, subset['normalized_macro_f1'].max(), float(np.max(upper)))
        y_min = min(y_min, float(np.min(lower)))

    _finalize(y_max, y_min=y_min,
              title=f"Normalized Macro F1 — band: {metric['label']}")
    path = os.path.join(FIGURES_DIR, f"02_comparison_normalized_f1_{metric['key']}.png")
    plt.savefig(path, dpi=300)
    plt.close()
    print(f"Saved: {path}")


def main():
    if not os.path.exists(INPUT_CSV):
        raise FileNotFoundError(f"Metrics CSV not found: {INPUT_CSV}")
    os.makedirs(FIGURES_DIR, exist_ok=True)

    df = pd.read_csv(INPUT_CSV)
    color_map = _color_map()

    # Figure A: no band (anchored at 0).
    plot_point(df, color_map)

    # Bootstrap stats (cached) -> one Figure B per dispersion metric.
    required_cols = {'norm_f1_mean', 'norm_f1_std', _pct_col(2.5), _pct_col(97.5)}
    boot_df = None
    if USE_CACHED_BOOTSTRAP and os.path.exists(BOOTSTRAP_CSV):
        cached = pd.read_csv(BOOTSTRAP_CSV)
        if required_cols.issubset(cached.columns):
            boot_df = cached
            print(f"Loaded cached bootstrap stats: {BOOTSTRAP_CSV}")
        else:
            print("Cached bootstrap CSV lacks dispersion stats (old format); recomputing...")
    if boot_df is None:
        boot_df = compute_bootstrap_ci(df)

    for metric in DISPERSION_METRICS:
        plot_dispersion(df, boot_df, color_map, metric)


if __name__ == "__main__":
    main()
