"""
Visualization script: Cross-Dataset Robustness (Macro F1 across layers).

Produces two figures per taxonomy from the cross-testing bootstrap results
generated by `interdataset_cross_test.py`:

  (A) `cross_test_{tax}.png`     -> cross-domain curves WITH 95% CI bands +
                                    in-domain baselines as POINT estimates
                                    (dashed, no band). Same as before.
  (B) `cross_test_{tax}_ci.png`  -> same, but the two in-domain baselines also
                                    get 95% bootstrap CI bands (Option 1).

In-domain CIs use Option 1 (test-set bootstrap): we DO NOT retrain. We reload
the saved probe (`.joblib`) and the activations (`.pkl`), reconstruct the exact
same train/test split used in training (same `random_state`, `stratify`,
rare-class filtering as `train_linear_probes_on_annotations.py`), and resample
the held-out test predictions to obtain a percentile CI on the macro F1. We use
the SAME stratified bootstrap as the cross-domain bands so both are comparable.
Results are cached to CSV.

Both figures keep the y-axis anchored at 0 (0 is the floor and always shown).
"""

import os
from collections import Counter

import numpy as np
import pandas as pd
import joblib
import matplotlib.pyplot as plt
import seaborn as sns
from tqdm import tqdm
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score
from sklearn.utils import resample

# --- CONFIGURACIÓN ---
LLM_USED = "Llama-2-7b-chat-hf"
BASE_DIR = "/home/jcuello/emotion_drift"
MODEL_DIM = 4096  # 5120 for Qwen2.5-14B
FIGURES_DIR = os.path.join(BASE_DIR, "figures", f"cross_testing_performance_{LLM_USED}")

# Cross-testing bootstrap results (from interdataset_cross_test.py)
INPUT_CSV = os.path.join(FIGURES_DIR, "cross_test_bootstrap_results.csv")

# Cached in-domain bootstrap CIs (computed here)
BOOTSTRAP_CSV = os.path.join(FIGURES_DIR, f"in_domain_baseline_bootstrap_ci_{LLM_USED}.csv")

TAXONOMIES = ['ekman_basic_emotions', 'plutchik_wheel']

MODELS_DIR = os.path.join(BASE_DIR, "models")

# Baseline point-estimate CSVs (in-domain macro F1, single split).
PATH_BASELINE_GEN = "results/probes_generated_prompts_Llama-2-7b-chat-hf/full_probing_metrics_Llama-2-7b-chat-hf_final_F1.csv"
PATH_BASELINE_HUMAN = "results/probes_human_centric_Llama-2-7b-chat-hf/full_probing_metrics_Llama-2-7b-chat-hf_final_F1.csv"

# Split reconstruction (must match train_linear_probes_on_annotations.py).
MIN_SAMPLES_REQUIRED = 5
SPLIT_RANDOM_STATE = 42
ACTIVATION_COL = "last_token_activation"

# Bootstrap settings (match interdataset_cross_test.py).
BOOTSTRAP_ITERATIONS = 10000
CONFIDENCE_LEVEL = 0.95
BOOTSTRAP_SEED = 42
USE_CACHED_BOOTSTRAP = True  # reuse the cached CI CSV if it exists

# In-domain baselines: how to reconstruct each one.
IN_DOMAIN = {
    "Generated": {
        "dataset": "generated_prompts",
        "data_path": os.path.join(
            BASE_DIR, "data", "03_activations",
            "generated_prompts_Llama-2-7b-chat-hf_20251014_203636_FINAL_WITH_RATINGS_AND_CATS.pkl",
        ),
        "baseline_csv": PATH_BASELINE_GEN,
        "color": "#1f77b4",
        "label": "Train: Generated $\\to$ Test: Generated",
    },
    "Human": {
        "dataset": "human_centric",
        "data_path": os.path.join(
            BASE_DIR, "data", "03_activations",
            "MERGED_andyzou_emotion_query_Llama-2-7b-chat-hf_FINAL.pkl",
        ),
        "baseline_csv": PATH_BASELINE_HUMAN,
        "color": "#ff7f0e",
        "label": "Train: Human $\\to$ Test: Human",
    },
}


# =========================================================================
# Bootstrap (Option 1: test-set resampling, no retraining)
# =========================================================================
def stratified_bootstrap_metric(y_true, y_pred, n_iterations, ci, seed):
    """Stratified bootstrap of macro F1, identical to interdataset_cross_test.py.

    Falls back to a simple (non-stratified) bootstrap when some class has < 2
    examples (stratification would fail).
    """
    alpha = (1.0 - ci) / 2.0
    rng = np.random.RandomState(seed)

    _, counts = np.unique(y_true, return_counts=True)
    stratify_possible = np.all(counts >= 2)

    stats = np.empty(n_iterations)
    for i in range(n_iterations):
        iter_seed = rng.randint(0, 2**32 - 1)
        if stratify_possible:
            y_t, y_p = resample(y_true, y_pred, replace=True,
                                stratify=y_true, random_state=iter_seed)
        else:
            y_t, y_p = resample(y_true, y_pred, replace=True,
                                random_state=iter_seed)
        stats[i] = f1_score(y_t, y_p, average="macro", zero_division=0)

    return (float(np.mean(stats)),
            float(np.percentile(stats, alpha * 100)),
            float(np.percentile(stats, (1.0 - alpha) * 100)))


def _build_test_split(sub, target, layer):
    """Reconstruct the exact (X_test, y_test) used in baseline training."""
    X_list, y_list = [], []
    for act_row, label in zip(sub["activations"], sub[target]):
        try:
            act = act_row.iloc[layer][ACTIVATION_COL]
        except Exception:
            continue
        if not isinstance(act, np.ndarray):
            continue
        if act.ndim > 1:
            act = act.squeeze()
        if act.shape == (MODEL_DIM,):
            X_list.append(act)
            y_list.append(label)

    if not X_list:
        return None, None
    X = np.stack(X_list)
    y_real = np.array(y_list)

    # Drop rare classes (identical to training).
    counts = Counter(y_real)
    drop = [c for c, n in counts.items() if n < MIN_SAMPLES_REQUIRED]
    if drop:
        keep = ~np.isin(y_real, drop)
        X, y_real = X[keep], y_real[keep]

    if len(X) == 0 or len(np.unique(y_real)) < 2:
        return None, None

    try:
        _, X_test, _, y_test = train_test_split(
            X, y_real, test_size=0.2,
            random_state=SPLIT_RANDOM_STATE, stratify=y_real,
        )
    except ValueError:
        return None, None
    return X_test, y_test


def compute_in_domain_bootstrap():
    """Test-set bootstrap CI for the in-domain baselines (no retraining)."""
    rows = []

    for train_source, cfg in IN_DOMAIN.items():
        data_path = cfg["data_path"]
        dataset = cfg["dataset"]

        if not os.path.exists(data_path):
            print(f"Advertencia: no se encontró el pkl de activaciones para "
                  f"'{train_source}': {data_path}. Se omite su CI in-domain.")
            continue
        if not os.path.exists(cfg["baseline_csv"]):
            print(f"Advertencia: no se encontró el baseline CSV para "
                  f"'{train_source}': {cfg['baseline_csv']}. Se omite su CI in-domain.")
            continue

        nested = pd.read_pickle(data_path)
        base_df = pd.read_csv(cfg["baseline_csv"])

        for target in TAXONOMIES:
            if target not in nested.columns:
                continue
            layers = sorted(base_df[base_df["taxonomy"] == target]["layer"].unique())
            if not layers:
                continue

            mask = nested[target].apply(lambda x: isinstance(x, list) and len(x) > 0)
            sub = nested[mask].copy()
            sub[target] = sub[target].str[0]

            for layer in tqdm(layers, desc=f"Bootstrap {train_source}/{target}"):
                model_path = os.path.join(
                    MODELS_DIR, f"{dataset}_{LLM_USED}_{target}_layer_{layer}.joblib"
                )
                if not os.path.exists(model_path):
                    continue

                X_test, y_test = _build_test_split(sub, target, layer)
                if X_test is None:
                    continue

                clf = joblib.load(model_path)
                y_pred = clf.predict(X_test)

                mean, low, high = stratified_bootstrap_metric(
                    y_test, y_pred, BOOTSTRAP_ITERATIONS, CONFIDENCE_LEVEL, BOOTSTRAP_SEED
                )
                rows.append({
                    "train_source": train_source,
                    "taxonomy": target,
                    "layer": int(layer),
                    "f1_mean": mean,
                    "f1_lower": low,
                    "f1_upper": high,
                })

    boot_df = pd.DataFrame(rows)
    boot_df.to_csv(BOOTSTRAP_CSV, index=False)
    print(f"CIs in-domain guardadas: {BOOTSTRAP_CSV}")
    return boot_df


# =========================================================================
# Plotting
# =========================================================================
def _plot_cross_domain(subset):
    """Plot the two cross-domain curves with their CI bands. Returns y-values."""
    y_values = []

    data_gh = subset[subset["train_source"] == "Generated"].sort_values("layer")
    plt.plot(data_gh["layer"], data_gh["f1_mean"],
             label="Train: Generated $\\to$ Test: Human",
             color="#1f77b4", linewidth=2)
    plt.fill_between(data_gh["layer"], data_gh["f1_lower"], data_gh["f1_upper"],
                     color="#1f77b4", alpha=0.25)
    y_values += data_gh["f1_lower"].tolist() + data_gh["f1_upper"].tolist()

    data_hg = subset[subset["train_source"] == "Human"].sort_values("layer")
    plt.plot(data_hg["layer"], data_hg["f1_mean"],
             label="Train: Human $\\to$ Test: Generated",
             color="#ff7f0e", linewidth=2)
    plt.fill_between(data_hg["layer"], data_hg["f1_lower"], data_hg["f1_upper"],
                     color="#ff7f0e", alpha=0.25)
    y_values += data_hg["f1_lower"].tolist() + data_hg["f1_upper"].tolist()

    return y_values


def _finalize(tax, y_values, title_suffix, save_name):
    """Common axis/legend styling. Y-axis anchored at 0 (the floor)."""
    plt.title(f"Cross-Dataset Robustness (Stratified Bootstrap 10k){title_suffix}\n"
              f"Taxonomy: {tax} | Metric: Macro F1", fontsize=14)
    plt.xlabel("Layer", fontsize=12)
    plt.ylabel("Macro F1-Score (with 95% CI)", fontsize=12)
    plt.legend(loc="lower right")

    if y_values:
        y_max = max(y_values)
        pad = max(y_max * 0.08, 0.02)
        plt.ylim(0, min(1.0, y_max + pad))  # 0 always shown; only top adjusts

    plt.grid(True, alpha=0.3)
    save_path = os.path.join(FIGURES_DIR, save_name)
    plt.tight_layout()
    plt.savefig(save_path, dpi=300)
    plt.close()
    print(f"Gráfico guardado: {save_path}")


def plot_figure_a(subset, tax):
    """Figure A: in-domain baselines as point estimates (no band)."""
    plt.figure(figsize=(12, 7))
    y_values = _plot_cross_domain(subset)

    for cfg in IN_DOMAIN.values():
        if not os.path.exists(cfg["baseline_csv"]):
            print(f"Advertencia: no se encontró baseline en {cfg['baseline_csv']}")
            continue
        data = pd.read_csv(cfg["baseline_csv"])
        data = data[data["taxonomy"] == tax].sort_values("layer")
        plt.plot(data["layer"], data["macro_f1"], label=cfg["label"],
                 color=cfg["color"], linewidth=2, linestyle="--")
        y_values += data["macro_f1"].tolist()

    _finalize(tax, y_values, "", f"cross_test_{tax}.png")


def plot_figure_b(subset, tax, boot_df):
    """Figure B: in-domain baselines also get bootstrap CI bands."""
    plt.figure(figsize=(12, 7))
    y_values = _plot_cross_domain(subset)

    for train_source, cfg in IN_DOMAIN.items():
        if not os.path.exists(cfg["baseline_csv"]):
            continue
        data = pd.read_csv(cfg["baseline_csv"])
        data = data[data["taxonomy"] == tax].sort_values("layer")
        plt.plot(data["layer"], data["macro_f1"], label=cfg["label"],
                 color=cfg["color"], linewidth=2, linestyle="--")
        y_values += data["macro_f1"].tolist()

        b = boot_df[(boot_df["train_source"] == train_source) &
                    (boot_df["taxonomy"] == tax)].sort_values("layer")
        if not b.empty:
            plt.fill_between(b["layer"], b["f1_lower"], b["f1_upper"],
                             color=cfg["color"], alpha=0.15)
            y_values += b["f1_lower"].tolist() + b["f1_upper"].tolist()

    _finalize(tax, y_values, " + in-domain CI", f"cross_test_{tax}_ci.png")


# =========================================================================
# Main
# =========================================================================
if __name__ == "__main__":
    if not os.path.exists(INPUT_CSV):
        print(f"Error: No se encontró el archivo de resultados en {INPUT_CSV}")
        print("Ejecuta primero el script de procesamiento (interdataset_cross_test.py).")
        exit()

    print(f"Cargando resultados de: {INPUT_CSV}")
    results_df = pd.read_csv(INPUT_CSV)

    sns.set_style("whitegrid")
    plt.rcParams.update({"font.size": 12})

    # In-domain bootstrap CIs (cached) for Figure B.
    if USE_CACHED_BOOTSTRAP and os.path.exists(BOOTSTRAP_CSV):
        boot_df = pd.read_csv(BOOTSTRAP_CSV)
        print(f"CIs in-domain cargadas desde caché: {BOOTSTRAP_CSV}")
    else:
        print("Calculando CIs in-domain (bootstrap estratificado, sin reentrenar)...")
        boot_df = compute_in_domain_bootstrap()

    for tax in TAXONOMIES:
        subset = results_df[results_df["taxonomy"] == tax]
        if subset.empty:
            print(f"No hay datos para la taxonomía: {tax}")
            continue

        plot_figure_a(subset, tax)          # Figure A (original)
        plot_figure_b(subset, tax, boot_df)  # Figure B (with in-domain CI)

    print("\nVisualización completada.")
