#%%
import os
import time
import requests
import re
from openai import OpenAI
import pandas as pd
import numpy as np
import json

def check_credits(api_key):
    response = requests.get(
    url="https://openrouter.ai/api/v1/key",
    headers={
        "Authorization": f"Bearer {api_key}"
    }
    )

    if response.status_code == 200:
        data = response.json().get("data")
        if data:
            limit = data.get('limit')
            usage = data.get('usage')
            remaining = limit - usage if limit is not None else 'Unlimited'
            print(f"Credit Limit: {limit}")
            print(f"Credit Usage: {usage}")
            print(f"Remaining Credit: {remaining}")
    else:
        print(f"Error: {response.status_code} - {response.text}")

def create_annotation_prompt(response_text, emotion_definitions):
    return f"""**Role:** You are an expert data analyst specializing in Natural Language Processing (NLP), with a focus on emotion annotation. Your task is to analyze responses generated by an artificial intelligence to identify the emotions they express.

    **Objective:** Evaluate the following text objectively to identify the predominant emotion or emotions it contains. Your analysis must be rigorous, unbiased, and based solely on the evidence within the text.

    1. **Definitions of Emotion Categories:**
    {emotion_definitions}
    
    2. **Annotation Rules:**
    You must follow these rules strictly:
    *   Evidence: Base your annotation exclusively on the content of the response. Do not infer emotions that are not supported by it.

    *   Handling Mixed Emotions:
    *   *   If a single emotion adequately describes the text's tone, use only that label.
    *   *   If two or more emotions are present, create a ranked list ordered by predominance. The first emotion in the list should be the strongest or most evident, followed by secondary emotions in descending order of importance.
    *   *   Your focus in these cases is to determine the overall 'weight' or 'proportion' of each emotion in the text as a whole. **Do not** list emotions in the order they appear. A brief emotion at the beginning is less important than a sustained emotion that permeates the rest of the text.
    *   *   If a text begins with an expression of "emotion 'A'", but the remaining 90% of the content elaborates on a topic with a clear tone of "emotion 'B'", then "emotion 'B'" is the most predominant emotion, and "emotion 'A'" is secondary. Then, **do not** list emotions in the order they appear. The output in this situation should be: ["emotion 'b'", "emotion 'a'"]

    *   Concise Justification: Provide a brief justification (1-2 sentences) that explains your choice, quoting or paraphrasing key phrases from the text that support your analysis.

    3. **Required Output Format:**
    Your response must be a single JSON code block with the following structure:

    ```json
    {{
    "emotions": ["Emotion_1", "Emotion_2", ...],
    "justification": "Your explanation here."
    }}```

    Your entire response must be ONLY in single JSON code block. Do not include any introductory or concluding sentences outside the code block.

    4. **Text to Annotate:**
    Here is the text to analyze:
    {response_text}
    """

def parse_json_from_response(response_content):
    """
    Extrae de forma robusta una cadena JSON de la respuesta de un LLM.
    Maneja respuestas que están envueltas en bloques de código Markdown.
    """
    # Buscar el inicio del bloque de código JSON
    json_block_start = response_content.find('```json')
    if json_block_start != -1:
        # Si encuentra el inicio del bloque, buscar el final y extraer el contenido
        json_start = response_content.find('{', json_block_start)
        json_end = response_content.rfind('}')
        if json_start != -1 and json_end != -1:
            json_str = response_content[json_start : json_end + 1]
            return json_str
            
    # Si no hay un bloque de código, buscar el primer y último bracket
    json_start = response_content.find('{')
    json_end = response_content.rfind('}')
    
    if json_start != -1 and json_end != -1:
        return response_content[json_start : json_end + 1]
        
    # Si no se encuentra ningún JSON, devolver la cadena original para que falle y se registre
    return response_content


def get_annotation(model_name, response_text, emotion_definitions):
    """
    Envía una solicitud de anotación a un modelo y devuelve la lista de emociones.
    Incluye manejo de errores para la llamada a la API y el parseo del JSON.
    """
    instruction_prompt = create_annotation_prompt(response_text, emotion_definitions)
    
    try:
        completion = client.chat.completions.create(
            model=model_name,
            messages=[{"role": "user", "content": instruction_prompt}],
            response_format={"type": "json_object"},
        )
        response_content = completion.choices[0].message.content
        
        json_string_to_parse = parse_json_from_response(response_content)

        try:
            data = json.loads(json_string_to_parse)
            emotions = data.get("emotions", [f"ERROR: 'emotion' key not found, {response_content}"])
            justification = data.get("justification", [f"ERROR: 'justification' key not found, {response_content}"])
            return emotions, justification
        except json.JSONDecodeError:
            print(f"  -> Error: No se pudo decodificar el JSON de la respuesta: {json_string_to_parse}")
            return [f"ERROR: Invalid JSON after cleaning: {response_content}"], [f"ERROR: Invalid JSON after cleaning: {response_content}"]
            
    except Exception as e:
        print(f"  -> Error: Falló la llamada a la API para el modelo {model_name}: {e}")
        return ["ERROR: API Call Failed"], ["ERROR: API Call Failed"]

def get_annotation_and_usage(api_key, model_name, response_text, emotion_definitions, user=False):
    """
    Envía una solicitud de anotación a Openrouter usando 'requests' y devuelve 
    la respuesta parseada junto con los datos de uso (costo, tokens).
    """
    instruction_prompt = create_annotation_prompt(response_text, emotion_definitions)
    error_return = (["ERROR"], ["ERROR"], {"cost": -1, "prompt_tokens": -1})

    try:
        if user:
            response = requests.post(
                url="https://openrouter.ai/api/v1/chat/completions",
                headers={
                    "Authorization": f"Bearer {api_key}",
                    "Content-Type": "application/json",
                },
                data=json.dumps({
                    "model": model_name,
                    "messages": [{"role": "user", "content": instruction_prompt}],
                    "usage": {"include":True},
                    "response_format": {"type": "json_object"},
                    "user": user
                })
            )
            response.raise_for_status()
            
            response_data = response.json()
            response_content = response_data['choices'][0]['message']['content']
            usage_data = response_data.get('usage', {})
            
            json_string_to_parse = parse_json_from_response(response_content)

            data = json.loads(json_string_to_parse)
            emotions = data.get("emotions", ["ERROR: Key 'emotions' not found"])
            justification = data.get("justification", ["ERROR: Key 'justification' not found"])
            return emotions, justification, usage_data, response_data
        
        else: 
            response = requests.post(
                url="https://openrouter.ai/api/v1/chat/completions",
                headers={
                    "Authorization": f"Bearer {api_key}",
                    "Content-Type": "application/json",
                },
                data=json.dumps({
                    "model": model_name,
                    "messages": [{"role": "user", "content": instruction_prompt}],
                    "usage": {"include":True},
                    "response_format": {"type": "json_object"}
                })
            )
            response.raise_for_status()
            
            response_data = response.json()
            response_content = response_data['choices'][0]['message']['content']
            usage_data = response_data.get('usage', {})
            
            json_string_to_parse = parse_json_from_response(response_content)

            data = json.loads(json_string_to_parse)
            emotions = data.get("emotions", ["ERROR: Key 'emotions' not found"])
            justification = data.get("justification", ["ERROR: Key 'justification' not found"])
            return emotions, justification, usage_data, response_data
        
    except requests.exceptions.HTTPError as e:
        print(f"  -> Error HTTP: {e.response.status_code} - {e.response.text}")
        return error_return
    except json.JSONDecodeError:
        print(f"  -> Error: No se pudo decodificar el JSON de la respuesta.")
        return error_return
    except Exception as e:
        print(f"  -> Error inesperado en la llamada a la API: {e}")
        return error_return

definitions_of_emotions = {"ekman_basic_emotions": f"""You must exclusively use the following taxonomy of emotions:
                           *    Anger: The response to an interference with our pursuit of a goal we care about. Anger can also be triggered by someone attempting to harm us (physically or psychologically) or someone we care about. In addition to removing the obstacle or stopping the harm, anger often involves the wish to hurt the target.
                           *    Disgust: Arises as a feeling of repulsion or aversion towards something offensive. We can feel disgusted by something we perceive with our physical senses (sight, smell, touch, sound, taste), by the actions or appearances of people, and even by offensive ideas. Disgust contains a range of states with varying intensities from mild dislike to intense loathing.
                           *    Enjoyment: Typically arising from connection or sensory pleasure. We use the word enjoyment to describe a family of related pleasurable states, everything from peace to ecstasy.
                           *    Fear: Arises in response to the threat of harm, either physical, emotional, or psychological, real or imagined. Fear activates impulses to freeze or flee, serving an important role in keeping us safe as it mobilizes us to cope with potential danger.
                           *    Sadness: The response to the loss of an important object or a person to which you are very attached. Serves an important role in signaling a need to receive help or comfort. Sadness describes the range of emotional states from mild disappointment to extreme despair and anguish.
                           *    Surprise: Arises when we encounter sudden and unexpected events. As the briefest of the emotions, its function is to focus our attention on determining what is happening and whether or not it is dangerous. In the moment before we figure out what is occurring, before we switch to another emotion or no emotion, surprise itself can feel good or bad.
                           *    Neutral: The absence of a predominant or clear emotion. The text is purely informational, factual, or does not express any discernible emotional state according to the categories above.""",
                           
                           "go_emotions": f"""You must exclusively use the following taxonomy of emotions:
                           *    Admiration: Finding something impressive or worthy of respect.
                           *    Amusement: Finding something funny or being entertained.
                           *    Anger: A strong feeling of displeasure or antagonism.
                           *    Annoyance: Mild anger, irritation.
                           *    Approval: Having or expressing a favorable opinion.
                           *    Caring: Displaying kindness and concern for others.
                           *    Confusion: Lack of understanding, uncertainty.
                           *    Curiosity: A strong desire to know or learn something.
                           *    Desire: A strong feeling of wanting something or wishing for something to happen.
                           *    Disappointment: Sadness or displeasure caused by the nonfulfillment of one’s hopes or expectations.
                           *    Disapproval: Having or expressing an unfavorable opinion.
                           *    Disgust: Revulsion or strong disapproval aroused by something unpleasant or offensive.
                           *    Embarrassment: Self-consciousness, shame, or awkwardness.
                           *    Excitement: Feeling of great enthusiasm and eagerness.
                           *    Fear: Being afraid or worried.
                           *    Gratitude: A feeling of thankfulness and appreciation.
                           *    Grief: Intense sorrow, especially caused by someone’s death.
                           *    Joy: A feeling of pleasure and happiness.
                           *    Love: A strong positive emotion of regard and affection.
                           *    Nervousness: Apprehension, worry, anxiety.
                           *    Optimism: Hopefulness and confidence about the future or the success of something.
                           *    Pride: Pleasure or satisfaction due to ones own achievements or the achievements of those with whom one is closely associated.
                           *    Realization: Becoming aware of something.
                           *    Relief: Reassurance and relaxation following release from anxiety or distress.
                           *    Remorse: Regret or guilty feeling.
                           *    Sadness: Emotional pain, sorrow.
                           *    Surprise: Feeling astonished, startled by something unexpected.
                           *    Neutral: The absence of a predominant or clear emotion. The text is purely informational, factual, or does not express any discernible emotional state according to the categories above.""",

                           "plutchik_wheel_of_emotions": f"""You must exclusively use the following taxonomy of emotions:
                           *    Fear: Its evolutionary function is protection. It is triggered by the perception of a threat or imminent danger, which the mind interprets as a “dangerous” situation. This emotion triggers a response of flight or avoidance, with the ultimate goal of preserving physical integrity. Its intensity ranges from mild apprehension to paralyzing terror.
                           *    Anger: Has the adaptive function of destroying an obstacle that prevents the achievement of a goal. It arises when an individual is confronted with what they perceive as an “Enemy” or a barrier, prompting them to respond with aggressive behaviors to remove that barrier. This emotional state can manifest itself in a range from annoyance to rage.
                           *    Joy: Its evolutionary function focuses on reproduction and affiliation. It motivates to seek and retain valuable resources, such as a potential partner, food, or a significant achievement, functioning as a signal of success or gain. It is associated with a cognition of “Possession” and promotes behaviors such as courtship or celebration. It ranges from calm to ecstasy.
                           *    Sadness: Has evolved to promote social reintegration. It is triggered by the loss of a person or a valuable resource, generated by a cognition of “isolation.” It functions as a distress, manifesting itself through behaviors such as crying, which seek to attract support and comfort to facilitate recovery and return to the community. Its intensity ranges from a pensive state to deep grief.
                           *    Trust: Its function is affiliation and the creation of strong social bonds. It emerges when interacting with someone who is perceived as a “friend” or ally. This emotion is the basis for cooperation and mutual support within a group, fostering caring and collaborative behaviors. Its spectrum ranges from acceptance to admiration.
                           *    Disgust: Has the adaptive function of provoking rejection. It acts as a defense mechanism against poisoning or disease, activating in response to a repulsive object that is interpreted as “poison”. The behavioral response is visceral and immediate, including removal from the object to avoid contact. Its range extends from boredom to loathing or total aversion.
                           *    Anticipation: Is oriented toward the future. Its evolutionary function is exploration and preparation. It drives to investigate new possibilities or territories, starting from the cognitive question “What's out there?” It encourages behaviors such as planning, examining, and mapping, allowing the individual to prepare to find resources or opportunities. It ranges from an interest to a state vigilance.
                           *    Surprise: Its main adaptive function is orientation. It is activated by a novel and unexpected stimulus, prompting the immediate question “What is this?”. It causes an instant pause in the current action, forcing the individual to refocus their attention to quickly reassess the environment and decide how to respond to the new information. Its intensity can range from distraction to amazement.
                           *    Neutral: The absence of a predominant or clear emotion. The text is purely informational, factual, or does not express any discernible emotional state according to the categories above."""
                           }


models_names = ["google/gemini-2.5-pro",
                "openai/gpt-5"]
#%%
#!! NO TE OLVIDES ESTO ACÁ!!!!! # Está la mía
api_key = "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"
client = OpenAI(
    base_url="https://openrouter.ai/api/v1",
    api_key=api_key
    )

## Cache hit with GPT-5
model_name = models_names[1]
emotions_definition = definitions_of_emotions["plutchik_wheel_of_emotions"]

df = pd.read_csv("/home/jcuello/emotion_drift/data/04_annotated/anotacion_manual_generated_responses - Sheet1.csv")
generated_responses = df["response_text"].tolist()

print("--- Iniciando prueba de caché con TEXTOS DIFERENTES ---")
print(f"Modelo a probar: {model_name}")
print("-" * 60)

# Variables para mantener el estado entre llamadas
first_response_data_raw = {}
cache_hits_log = [] # Lista para registrar los cache hits

# Bucle para recorrer todas las respuestas generadas
for index, texto_a_probar in enumerate(generated_responses):
    
    print(f"{index + 1}. Anotando el texto: '{texto_a_probar[:50]}...'")
    
    # Se obtiene el ID de la respuesta anterior, si existe
    user_id = first_response_data_raw.get("id")
    
    # Se llama a la función de anotación.
    # Si user_id tiene un valor, se pasa a la función. Si es None (en la primera vuelta), no se pasa el parámetro.
    if user_id:
        print(f" User id: {user_id}")
        emotions, just, usage, response_data_raw = get_annotation_and_usage(
            api_key, 
            model_name, 
            texto_a_probar, 
            emotions_definition, 
            user=user_id
        )
    else:
        print(f" User id: {user_id}")
        # Primera llamada, se omite el parámetro 'user' para que use el default
        emotions, just, usage, response_data_raw = get_annotation_and_usage(
            api_key, 
            model_name, 
            texto_a_probar, 
            emotions_definition
        )

        # Se actualiza la variable con los datos de la respuesta actual para la siguiente iteración
        first_response_data_raw = response_data_raw
    
    costo = usage.get('cost', -1)
    
    print(f"   -> Costo TOTAL de la llamada {index + 1}: ${costo:.8f}")
    
    # Se determina si hubo un cache hit y se registra
    prompt_tokens_details = usage.get("prompt_tokens_details", {})
    is_cache_hit = prompt_tokens_details.get("cached_tokens", 0) > 0
    cache_hits_log.append(is_cache_hit)
    
    print(f'   -> Costo de tokens en inpunt: {usage.get("cost_details").get("upstream_inference_prompt_cost")}')
    print(f'   -> Tokens en cache: {prompt_tokens_details.get("cached_tokens")}')
    print(f'   -> Cache hit: {is_cache_hit}')
    print("-" * 60)

# --- CÁLCULO DE LA MÉTRICA FINAL ---
print("\n--- Métrica de Cache Hit Rate ---")
total_calls = len(cache_hits_log)

if total_calls > 0:
    total_hits = sum(cache_hits_log)  # sum() trata True como 1 y False como 0
    cache_hit_rate = (total_hits / total_calls) * 100
    
    print(f"Total de llamadas realizadas: {total_calls}")
    print(f"Total de aciertos de caché (cache hits): {total_hits}")
    print(f"Cache Hit Rate: {cache_hit_rate:.2f}%")
#%%
## Batching with GPT-5 (OpenAI key needed)
from openai import OpenAI

#!! NO TE OLVIDES ESTO ACÁ!!!!! # Está la mía
api_key = "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"

client = OpenAI(api_key=api_key)

batch_input_file = client.files.create(
    file=open("batch_job_test.jsonl", "rb"),
    purpose="batch"
)

batch_input_file_id = batch_input_file.id
client.batches.create(
    input_file_id=batch_input_file_id,
    endpoint="/v1/chat/completions",
    completion_window="24h",
    metadata={
        "description": "batching tests"
    }
)

batch = client.batches.retrieve("batch_68c46af440688190bef84607a8a02250")
file_response = client.files.content("file-5VQuZx5M27y7CBSt3gJkg7")
print(file_response.text)
#%%
## Batching + attempt of caching with GPT-5 (OpenAI key needed)
from openai import OpenAI
import pandas as pd
import json

#!! NO TE OLVIDES ESTO ACÁ!!!!!
api_key = ""

df = pd.read_csv("/home/jcuello/emotion_drift/data/04_annotated/anotacion_manual_generated_responses - Sheet1.csv")
generated_responses = df["response_text"].tolist()

model_name = "gpt-5"
emotions_definition = definitions_of_emotions["plutchik_wheel_of_emotions"]

path_jsonl = "batch_annotation_jobs_test.jsonl"

batch_requests = []
# Itera sobre cada texto a analizar
for i, response_text in enumerate(generated_responses):
    # Crea el prompt específico para este texto
    instruction_prompt = create_annotation_prompt(response_text, emotions_definition)
    
    # Construye el diccionario para la solicitud del lote
    request = {
        "custom_id": f"request-{i}",
        "method": "POST",
        "url": "/v1/chat/completions",
        "body": {
            "model": model_name,
            "messages": [
                {"role": "user", "content": instruction_prompt}
            ],
            "response_format": {"type": "json_object"},
            "prompt_cache_key": "gen-1757602875-878DOlG67xz757xY9tkV" #!! This is random, maybe I should use the first response's id?
        }
    }
    batch_requests.append(request)

with open(path_jsonl, 'w') as f:
    for req in batch_requests:
        # Convierte el diccionario a una cadena JSON y lo escribe en una nueva línea
        f.write(json.dumps(req) + '\n')

client = OpenAI(api_key=api_key)

batch_input_file = client.files.create(
    file=open(path_jsonl, "rb"),
    purpose="batch"
)

batch_input_file_id = batch_input_file.id
client.batches.create(
    input_file_id=batch_input_file_id,
    endpoint="/v1/chat/completions",
    completion_window="24h",
    metadata={
        "description": "batching tests 2"
    }
)

# Último paso de retrieve
# file_response = client.files.content("file-4hzDsjRTx1WFyRLWcDH5tC")
# %%
